name: selection_menu
description: A highly customizable selection/select menu, that opens/closes with a tap of trigger, optionally provides search.
version: 2.0.2
homepage: https://github.com/HussainTaj-W/flutter-package-selection_menu

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
